<a href="https://colab.research.google.com/github/ryukkt62/ktkim/blob/main/split_%ED%95%A8%EC%88%98_%EB%A7%8C%EB%93%A4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. split 함수 만들기(다:1)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([1,2,3,4,5,6,7,8,9,10])
dataset

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# time_steps는 x의 row를 몇개씩 넣을건지
def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset)-1:
            break
        tmp_x = dataset[i:end_number]
        tmp_y = dataset[end_number]

        x.append(tmp_x)
        y.append(tmp_y)

    return np.array(x), np.array(y)
x, y = split_xy1(dataset,4)
print('x',"\n",x, "\n", 'y', "\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]] 
 y 
 [[ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
x.shape:  (6, 4, 3)
y.shape:  (6, 3)


# 2. split 함수 만들기2(다:다)

In [ ]:
# time_steps는 x의 row를 몇개씩 넣을건지
# y_columns는 y의 row를 몇개씩 넣을건지
def split_xy2(dataset, time_steps, y_columns):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_columns
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i : x_end_number]
        tmp_y = dataset[x_end_number : y_end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 4
y_column = 2
x, y = split_xy2(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 
 y 
 [[ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]
x.shape:  (5, 4)
y.shape:  (5, 2)


# 3. split 함수 만들기3(다입력,다:1)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
 [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])

print("dataset.shape: ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape: ", dataset.shape)

dataset.shape:  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape:  (10, 3)


In [ ]:
# time_steps는 x의 row를 몇개씩 넣을건지
# y_columns는 y의 row를 몇개씩 넣을건지
def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1

        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 3
y_column = 1
x, y = split_xy3(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]

 [[ 8 18]
  [ 9 19]
  [10 20]]] 
 y 
 [[23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
x.shape:  (8, 3, 2)
y.shape:  (8, 1)


# 4. split 함수 만들기4(다입력,다:다)

In [ ]:
def split_xy4(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1

        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 3
y_column = 2
x, y = split_xy4(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]] 
 y 
 [[23 24]
 [24 25]
 [25 26]
 [26 27]
 [27 28]
 [28 29]
 [29 30]]
x.shape:  (7, 3, 2)
y.shape:  (7, 2)


# 5. split 함수 만들기4(다입력,다:다)

In [ ]:
def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i+time_steps
        y_end_number = x_end_number + y_column

        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :]
        tmp_y = dataset[x_end_number:y_end_number,:]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 3
y_column = 2
x, y = split_xy5(dataset, 3, 1)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]

 [[ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]] 
 y 
 [[[ 4 14 24]]

 [[ 5 15 25]]

 [[ 6 16 26]]

 [[ 7 17 27]]

 [[ 8 18 28]]

 [[ 9 19 29]]

 [[10 20 30]]]
x.shape:  (7, 3, 3)
y.shape:  (7, 1, 3)
