# 딥러닝 온라인 1:1 과외반 <Level 3> 과제

(이 쥬피터 노트북은 다음의 링크 <b>https://bit.ly/dsd-0301</b> 에서 다운받으실 수 있습니다)

넘파이(Numpy) 패키지는 Numerical Python의 줄임말로, 딥러닝 분야에서 매우 유용하게 사용되는 패키지입니다. 딥러닝 분야뿐만 아니라 데이터 분석에도 핵심적으로 사용되는 패키지이므로 필수적으로 이해하고 있어야 합니다. 

넘파이(Numpy)가 자주 사용되는 이유는 딥러닝에 사용되는 데이터구조인 벡터, 행렬 그리고 3차원 이상 텐서를 표현하고 활용할 수 있도록 여러가지 기능을 제공해주기 때문입니다.
벡터를 표현하기위해 ```numpy.array```를 선언할 수 있고, 행렬을 표현하기 위해 ```numpy.matrix```를 선언할 수 있으며 이를 이용하면 사칙연산을 포함한 다양한 함수들을 사용할 수 있는데요, 예를들면 ```numpy.zeros()```, ```numpy.sum()```, ```numpy.mean()```, ```numpy.argmax()```를 포함한 유용한 함수들이 무수히 많습니다. 또한 벡터화함으로써 딥러닝의 실행속도를 개선하거나 코드를 간결하게 줄여주기도 합니다.

그러므로 넘파이(Numpy)패키지의 다양한 함수에 익숙해지는 것은 무엇보다도 중요합니다. 하기에 제시한 15개의 문제를 프로그래밍 언어 파이썬(```Python```)과 파이썬의 넘파이(Numpy) 패키지를 활용해 풀어주세요.

문제를 풀 때 다른 자료를 참고하거나, 구글에 검색하는 것 모두 허용합니다. (문제 중에는 구글에 검색하지 않으면 풀 수 없는 문제도 준비해놓았습니다) 관련자료는 [Numpy tutorial](https://numpy.org/devdocs/user/quickstart.html)을 강력 추천합니다. 또는 이전 수업에서 학습한 내용을 참고하는 것도 적극 추천합니다.

### 넘파이(Numpy) 불러오기

먼저 넘파이(Numpy) 패키지를 불러오겠습니다. 패키지를 불러올 때는 ```import```를 사용합니다.  

넘파이(Numpy) 패키지를 파이썬에서 사용할 때는 관용적으로 ```np```라는 이름을 사용하곤 합니다. 우리도 np라는 이름으로 불러와서 실습을 진행해 볼건데요, 이렇게 패키지 이름을 지정해주면 함수를 사용할 때 좀 더 간략하게 ```numpy.sum()``` 대신 ```np.sum()```으로 사용할 수 있습니다.

**1. Numpy패키지를 np라는 이름으로 불러오세요.**

In [ ]:
# numpy를 np라는 이름으로 import 해옵니다.
import numpy as np

### 벡터 표현하기

벡터를 표현하기 위해서 넘파이(Numpy)에서 제공해주는 배열(```array```)을 이용할 수 있습니다.  
어떤 함수를 사용하는지에 따라 배열을 생성할 때 직접 값을 초기화 할지 0으로 모든 값을 초기화 할지 등을 정할 수 있습니다. 배열 생성에 관한 자세한 정보는 [다음의 링크](https://numpy.org/devdocs/user/quickstart.html#array-creation)를 참고해주세요. 행렬을 생성할 때도 모두 응용될 수 있습니다.

**2. 크기가 15이고 모든 값이 0으로 채워진 배열을 하나 생성하세요.**

최종적으로 다음의 결과가 나와야 합니다.
```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

In [ ]:
# numpy의 zeros함수를 사용하여 크기가 15이고 0으로 채워진 배열을 생성합니다.
# 그리고 이 결과를 data2변수에 할당합니다.
data2 = np.zeros(15)

# data2를 출력합니다.
data2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**2-1 위에서 생성한 생성한 데이터의 크기를 출력하세요.**
 
최종적으로 15가 출력됩니다. 크기를 출력할 때는 파이썬의 [len](https://wikidocs.net/32#len)을 쓰기도 하지만, 넘파이(Numpy)의 [size](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html)를 사용하기도 합니다.

In [ ]:
# numpy의 size함수를 이용하여 data2의 크기를 출력합니다.
np.size(data2)

15

### 행렬 표현하기

**3. 1행이 100, 200 이고 2행이 300, 400인 행렬을 생성하세요.**

Numpy에서 행렬을 표현할 때는 ```matrix```함수를 이용할 수 있습니다. 최종적으로 다음의 결과가 나와야 합니다.
```
matrix([[100, 200],  
        [300, 400]])  
```

In [ ]:
# numpy의 matrix함수를 사용하여 1행이 100, 200 2행이 300, 400인 행렬을 생성합니다.
# 그리고 이 결과를 data3변수에 할당합니다.
data3 = np.matrix([[100, 200], [300, 400]])

# data3를 출력합니다.
data3

matrix([[100, 200],
        [300, 400]])

**3-1 생성한 데이터가 몇행 몇열인지 출력하세요.**

실행 결과로 ```(2, 2)```가 출력되어야 합니다. 보통 이런 경우에는 넘파이(Numpy)의 [shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html)함수를 사용합니다.

In [ ]:
# numpy의 shape함수를 이용하여 data3의 형태를 출력합니다.
np.shape(data3)

(2, 2)

### 벡터와 행렬 응용하기

지금부터는 딥러닝에 활용되기 위한 넘파이(Numpy)의 기본적인 기능을 알아보겠습니다.   

사용할 데이터들을 깔끔하게 전처리하고 딥러닝 알고리즘을 효율적으로 구현하기 위해서는 Numpy에서 제공하는 기능들을 잘 숙지하여 활용하는 것이 좋습니다.   

벡터와 행렬 구조에서 인덱싱(indexing)과 슬라이싱(slicing)을 익히고 어떤 유용한 함수들이 있는지 알아보겠습니다.

**4. 크기가 10이고 모든 값이 0으로 채워진 배열을 생성한 뒤 1번째, 2번째 10번째 값을 각각 1, 2, 10으로 수정하세요.**

넘파이(Numpy)에서 제공하는 ```array``` 형식은 파이썬의 리스트처럼 index를 이용할 수 있습니다. 자세한 정보는 [다음의 링크](https://numpy.org/devdocs/user/quickstart.html#indexing-slicing-and-iterating)를 참고하세요.

최종적으로 다음의 결과가 나와야 합니다.
```
array([ 1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.])
```

In [ ]:
# numpy의 zeros함수를 사용하여 크기가 10이고 0으로 채워진 배열을 생성합니다.
# 그리고 이 결과를 data4변수에 할당합니다.
data4 = np.zeros(10)

# data4의 0번째칸에 1을 넣습니다.
data4[0] = 1

# data4의 1번째칸에 2을 넣습니다.
data4[1] = 2

# data4의 9번째칸에 10을 넣습니다.
data4[9] = 10

# data4를 출력합니다.
data4

array([ 1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.])

**5. 4번에서 생성한 배열에서 값이 0이 아닌 index를 출력해주세요.**

이 경우에는 넘파이(Numpy)의 [nonzero](https://docs.scipy.org/doc/numpy/reference/generated/numpy.nonzero.html)를 사용합니다. 최종적으로 다음의 결과가 나와야 합니다.
```
array([0, 1, 9])
```

In [ ]:
# numpy의 nonzero함수를 사용하여 data4에서 값이 0이 아닌 index를 찾아 출력합니다.
np.nonzero(data4)

(array([0, 1, 9]),)

**5-1. 4번에서 생성한 배열의 index를 거꾸로 출력해주세요.**

자세한 사항은 넘파이(Numpy)의 [indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html) 관련 문서를 살펴보세요. 만일 이 문서에서도 정답을 찾을 수 없으면, 구글에서 검색해보시는걸 추천 드립니다. (예시 키워드: Numpy reverse indexing) 최종적으로 다음의 결과가 나와야 합니다.
```
array([10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.])
```

In [ ]:
# data4의 값을 거꾸로 출력합니다.
data4[::-1]

array([10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.])

**6. 10부터 44까지의 정수가 담긴 배열을 생성하세요.**

보통 이런 경우는 넘파이(Numpy)의 [arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)를 사용합니다. 최종적으로 다음의 결과가 나와야 합니다.

```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44])
```

In [ ]:
# numpy의 arange함수를 사용하여 10부터 44까지의 정수가 담긴 배열을 생성합니다.
data6 = np.arange(10, 45)

# data6을 출력합니다.
data6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44])

**7. 6번에서 생성한 배열을 행이 7개인 행렬의 모양으로 바꿔주세요.**

이런 경우에는 보통 넘파이(Numpy)의 [reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)를 사용합니다. 결과는 다음과 같습니다.  

In [ ]:
# numpy의 reshape함수를 사용하여 행이 7개인 행렬로 바꿔줍니다.
data6.reshape(7, -1)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

**8. 랜덤한 값이 담긴 4x3크기의 행렬을 생성하세요.**

자세한 사항은 넘파이(Numpy)의 [Random sampling](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html) 문서를 참고하세요. 예를 들어 다음의 결과가 나와야 합니다. (4x3 크기만 일치하면 될 뿐, 랜덤 값이기 때문에 내부 값은 달라도 큰 문제 없습니다)

```
array([[0.4402027 , 0.95203021, 0.05768148],
       [0.46816255, 0.71225697, 0.23287108],
       [0.67228134, 0.81530935, 0.29613427],
       [0.34000567, 0.86244685, 0.31680388]])
```

In [ ]:
# numpy의 random.random함수를 사용하여 행의 크기가 4, 열의 크기가 3인 행렬을 만들고 랜덤한 수로 초기화 합니다.
data8 = np.random.random((4, 3))

# data8을 출력합니다.
data8

array([[0.4402027 , 0.95203021, 0.05768148],
       [0.46816255, 0.71225697, 0.23287108],
       [0.67228134, 0.81530935, 0.29613427],
       [0.34000567, 0.86244685, 0.31680388]])

**9. 8번에서 생성한 행렬의 값 중 최솟값과 최대값을 각각 출력해주세요.**

자세한 사항은 [다음의 링크](https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html)를 참고해주세요.

In [ ]:
# numpy의 min함수를 사용하여 data8의 최솟값을 출력합니다.
data8.min()

0.09837452338682229

In [ ]:
# numpy의 max함수를 사용하여 data8의 최대값을 출력합니다.
data8.max()

0.952030206481001

**9-1. 8번에서 생성한 행렬에서 각 행의 최대값을 나타내는 열이 몇번째 열인지 출력해주세요.**

이런 경우에는 보통 [argmax](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html)라는 기능을 사용합니다. 최종적으로 실행결과로 4개의 숫자값이 나와야 합니다.

In [ ]:
# numpy의 argmax함수를 사용하여 data8에서 최대값을 가진 index를 출력합니다.
# axis=1 옵셥을 주어 각 행의 최대값을 구해줍니다.
data8.argmax(axis=1)

array([1, 1, 1, 1])

**10. 8번에서 생성한 행렬 값의 평균값(mean)과 합계(sum)를 각각 출력해주세요.**

자세한 사항은 [다음의 링크](https://www.pythonprogramming.in/numpy-aggregate-and-statistical-functions.html)를 참고해주세요.

In [ ]:
# numpy의 mean함수를 사용하여 data8의 평균값을 출력합니다.
data8.mean()

0.5138488625135942

In [ ]:
# numpy의 sum함수를 사용하여 data8의 합계를 출력합니다.
data8.sum()

6.16618635016313

**11. 8번에서 생성한 행렬과 ```[1, 2, 3, 4]```가 담긴 넘파이(Numpy) 배열의 내적(dot product)을 구하세요.**


앞서 공부한대로, 넘파이(Numpy)의 [dot](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.dot.html)을 실행하면 됩니다. 실행결과로 3개의 숫자값이 나와야 합니다.

In [ ]:
# numpy의 array를 이용하여 1, 2, 3, 4가 담긴 배열을 선언합니다.
# 그리고 이 결과를 data11변수에 할당합니다.
data11 = np.array([1, 2, 3, 4])

# numpy의 dot을 이용하여 data8과 data11의 내적을 구합니다.
# data8을 전치하여 내적연산의 형태를 맞춰줍니다.
np.dot(data8.T, data11) 

array([4.75339452, 8.27225958, 2.67904196])

**12. 0부터 9사이의 랜덤한 정수값이 담긴 배열 2개를 생성하세요.**

자세한 사항은 넘파이(Numpy)의 [Random sampling](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html) 문서를 참고하세요. 최종적으로 다음의 결과가 출력되어야 합니다.
```
[6 2 7 9 7 8 8 9 8 2] [8 5 7 1 5 7 2 4 4 8]
```

In [ ]:
# numpy의 random.randint를 사용하여 크기가 10이고, 0부터 9사이의 랜덤한 수로 초기화하여 배열을 생성합니다.
# 그리고 이 결과를 A와 B에 각각 할당합니다.
A = np.random.randint(0, 10, 10)
B = np.random.randint(0, 10, 10)

# A와 B를 출력합니다.
print(A, B)

[6 3 2 6 1 4 5 5 7 4] [5 1 3 4 3 0 4 7 5 5]


**12-1 12번에서 생성한 두 배열에서 공통된 값을 출력하세요.**

이 경우에는 넘파이(Numpy)의 [intersect1d](https://docs.scipy.org/doc/numpy/reference/generated/numpy.intersect1d.html)를 사용합니다. 최종적으로 다음의 결과가 출력되어야 합니다.

```
array([2, 7, 8])
```

In [ ]:
# numpy의 intersect1d함수를 이용하여 두 배열의 교집합을 출력합니다.
np.intersect1d(A, B)

array([1, 3, 4, 5, 7])

**13. 다음 그림과 같이 테두리가 1이고 안은 0으로 채워진 5x5크기의 행렬을 생성하세요. 단, 슬라이싱을 사용하세요.**


넘파이(Numpy)의 [ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)함수를 사용하여 5X5행렬을 생성한 뒤 슬라이싱으로 0을 채워 넣습니다. 슬라이싱을 하는 방법은 파이썬 리스트를 슬라이싱 하는 것과 매우 유사합니다. 슬라이싱에 대한 자세한 정보는 [다음의 링크](https://numpy.org/devdocs/user/quickstart.html#indexing-slicing-and-iterating)를 참고하세요. 최종적으로 다음의 결과가 나와야 합니다.

```
    [1., 1., 1., 1., 1.]  
    [1., 0., 0., 0., 1.]  
    [1., 0., 0., 0., 1.]  
    [1., 0., 0., 0., 1.]  
    [1., 1., 1., 1., 1.]  
```

In [ ]:
# numpy의 ones함수를 사용하여 행의 크기가 5, 열의 크기가 5이고 모든 값이 1로 채워진 행렬을 생성합니다.
data13 = np.ones((5, 5))

# 행의 1번째 칸부터 -1번째 칸까지, 열의 1번째 칸부터 -1번째 칸까지 0으로 변경해줍니다.
data13[1:-1, 1:-1] = 0

# data13을 출력합니다.
data13

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**14. 다음 그림과 같이 0, 1이 반복되는 5x5크기의 행렬을 생성하세요.**

넘파이(Numpy)의 [zeros](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html) 함수를 사용하여 5X5행렬을 생성한 뒤 슬라이싱으로 1을 채워 넣습니다. 슬라이싱을 하는 방법은 파이썬 리스트를 슬라이싱 하는 것과 매우 유사합니다. 슬라이싱에 대한 자세한 정보는 [다음의 링크](https://numpy.org/devdocs/user/quickstart.html#indexing-slicing-and-iterating)를 참고하세요. 최종적으로 다음의 결과가 나와야 합니다.

```
    [0., 1., 0., 1., 0.]
    [1., 0., 1., 0., 1.]
    [0., 1., 0., 1., 0.]
    [1., 0., 1., 0., 1.]
    [0., 1., 0., 1., 0.]
```

In [ ]:
# numpy의 zeros함수를 사용하여 행의 크기가 5, 열의 크기가 5이고 모든 값이 0으로 채워진 행렬을 생성합니다.
data14 = np.zeros((5, 5))

# 행의 두번째칸(index : 1)부터 마지막칸까지 2칸단위로, 열의 첫번째칸부터 마지막칸까지 2칸단위로 1을 넣습니다.
data14[1::2, ::2] = 1

# 행의 첫번째칸부터 마지막칸까지 2칸단위로, 열의 두번째칸(index : 1)부터 마지막칸까지 2칸단위로 1을 넣습니다.
data14[::2, 1::2] = 1

# data14를 출력합니다.
data14

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

### 날짜 표현하기

**15. 오늘 날짜와 내일 날짜를 출력하세요. (형식 : YYYY-MM-DD)**

넘파이(Numpy)에서는 [datetime64](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html)라는 데이터 타입으로 날짜를 표현하는 기능을 기본적으로 제공하고 있습니다. 이를 활용하여 오늘 날짜와 내일 날짜를 직접 표현해보세요. Datetime에 대한 자세한 정보는 [다음의 링크](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html)를 참고하세요.

In [ ]:
# numpy의 datetime64함수를 사용합니다.
# 옵션으로 'today'를 적으면 오늘 날짜를 나타낼 수 있습니다.
today = np.datetime64('today')

# timedelta64함수의 옵션으로 1, 'D'를 적으면 하루를 의미합니다.
# 오늘 날짜에 하루를 더해 내일 날짜를 나타낼 수 있습니다.
tomorrow = np.datetime64('today') + np.timedelta64(1, 'D')

# today와 tomorrow변수를 출력합니다.
print(today, tomorrow)

2019-11-13 2019-11-14


## 제출

과제를 다 끝내셨으면 http://bit.ly/ds-assignment 에서 안내에 따라 과제를 제출하여 주세요! 과제를 제출해주시면 검토 결과를 드리고 다음 레벨에 초대해드립니다. 

과제 제출 후에 늦어도 24시간 이내에는 회신을 드립니다. 다만 과제의 난이도나 풀이에 따라 다소 시간이 걸릴 수 있다는 점 양해 부탁드립니다. 혹시나 다음 레벨로 초대를 못 받은 분들은 채널에 있는 튜터분에게 문의 주시면 다음 채널을 오픈해드립니다.

수업이나 과제 관련 질문, 수료증 문의 등은 담당 튜터(조교)에게 문의 주세요. 영수증 발급 등의 문의는 support@dsschool.co.kr 로 메일 주시면 담당자분이 응대해주실 겁니다. 기타 궁금한 사항은 슬랙으로 문의 주세요!