# 딥러닝 온라인 1:1 과외반 <Level 2> 과제

(이 쥬피터 노트북은 다음의 링크 https://bit.ly/dsd-0202 에서 다운받으실 수 있습니다)

지금까지 퍼셉트론(Perceptron)과 이 알고리즘을 학습하는 알고리즘들에 대해 배웠습니다.  
이번 과제에서는 실습 데이터를 사용하여 직접 알고리즘을 구현해보도록 하겠습니다. 

## Boston Housing Dataset

이번 과제는 관련 데이터를 활용하여 보스턴 시의 주택 가격을 예측하는 문제를 푸는 것입니다. Single-layer Perceptron를 활용하여 보스턴 시의 주택 가격을 예측하는 알고리즘을 구현하세요.

각 컬럼에 대한 설명은 다음과 같습니다. 출처: [ai-times](http://ai-times.tistory.com/431)

  * **CRIM**: 자치 시(town) 별 1인당 범죄율
  * **ZN**: 25,000 평방피트를 초과하는 거주지역의 비율
  * **INDUS**: 비소매상업지역이 점유하고 있는 토지의 비율
  * **CHAS**: 찰스강의 경계에 위치해 있으면 1, 그렇지 않으면 0
  * **NOX**: 10ppm당 농축 일산화질소
  * **RM**: 주택 1가구당 평균 방의 개수
  * **AGE**: 1940년 이전에 건축된 소유주택의 비율
  * **DIS**: 5개의 보스턴 직업센터까지의 접근성 지수
  * **RAD**: 방사형 도로까지의 접근성 지수
  * **TAX**: 10,000 달러 당 재산세율
  * **PTRATIO**: 자치 시(town)별 학생/교사 비율
  * **B**: 1000(Bk-0.63)^2 (여기서 Bk는 자치시별 흑인의 비율)
  * **LSTAT**: 모집단의 하위계층 비율(%)
  * **MEDV**: 본인 소유의 주택 가격(중앙값) (단위: $1,000)
  
**주의 사항**
  * **MEDV**가 label(y), 나머지가 feature(X)라고 가정하고 문제를 풀어주세요.
  * **한 번에 너무 잘 풀려고 하지 마세요.** 먼저 동작하는 코드를 만드는데 집중하고, 그 다음에 코드를 개선하세요.
  * 현실 데이터는 우리가 이전에 다룬 가상의 데이터와 다르기 때문에 error가 0에 가깝게 내려가지 않을 수도 있습니다.  
   **Boston Housing Dataset에서 error는 5 (=$5,000) 미만으로 내려가면 충분합니다. ** (```error = np.abs(y_predict - y).mean()```)
  * error가 수렴하지 않고 발산한다면, **learning_rate를 작게 조정해보세요**.

### Import Packages

In [1]:
# 사용할 패키지들을 import 합니다.
# scikit-learn (sklearn)은 몇가지 데이터셋을 제공합니다. 
# 보스턴 시의 주택 가격 및 관련 데이터도 그 중 하나입니다.
# 보스턴 데이터는 sklearn.datasets의 load_boston으로 불러올 수 있습니다.

# load_boston을 불러옵니다.
from sklearn.datasets import load_boston

# numpy를 불러옵니다.
# numpy는 고성능의 수치계산을 위해 사용하는 기본적이면서도 중요한 패키지입니다. 다양하고 빠른 연산을 지원합니다.
# 특히 딥러닝(Deep Learning)에서는, numpy를 이용한 '연산의 벡터화' 개념이 중요합니다.
# 따라서 뒤의 <Level 3>에서 numpy를 더욱 자세히 배우게 됩니다.
import numpy as np

# pandas를 불러옵니다.
# pandas는 데이터 분석에 널리 사용되는 패키지입니다.
# 엑셀과 비슷한 형태로 사용자 친화적일 뿐만 아니라, 제공하는 기능이 많고 특히 대용량 데이터 분석이 용이하다는 장점이 있습니다.
# numpy와 pandas는 매우 중요한 패키지로 앞으로 열심히 연습하면 좋습니다.
import pandas as pd

### Load Datasets

In [2]:
# 보스턴 데이터를 불러옵니다.
boston = load_boston()

In [3]:
# 우리가 불러올 데이터는 딕셔너리(dictionary) 형태이며, 모든 정보가 한 번에 저장되어 있습니다.
# 따라서, 먼저 key를 조회해 어떤 데이터가 담겨있는 지 살펴볼 수 있습니다.
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [4]:
# 반복문을 사용해 실제로 사용할 데이터를 살펴볼 수 있습니다. 단, 데이터의 양이 많을 수 있으므로 생략해도 좋습니다.
# 'data'에는 우리가 feature(X)로 사용할 데이터, 'target'에는 label(y)이 들어있음을 알 수 있습니다.
for key in boston.keys():
    print(key)
    print(boston[key])
    print('\n') # '\n'은 줄바꿈을 의미합니다.

data
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


target
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5

In [5]:
# feature(X)로 사용할 데이터('data')를 X에 저장합니다.
X = boston["data"]

# X의 shape을 출력하여 확인합니다.
print(X.shape)

# X의 첫 데이터를 확인합니다.
X[0]

(506, 13)


array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [6]:
# label('target')을 y에 저장하고 마찬가지로 shape과 처음 10개 값을 확인합니다.
y = boston["target"]

print(y.shape)
y[0:10]

(506,)


array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

In [7]:
# 모델을 학습시키기 위해 DataFrame 형태로 변환합니다.
# 이때, 컬럼명을 지정해줄 수 있는데,
# 처음 불러온 딕셔너리 데이터(boston)에 담겨있던 'feature_names'를 활용할 수 있습니다.
data = pd.DataFrame(X, columns=boston["feature_names"])

# label명은 "MEDV"로 정의합니다.
# "MEDV"컬럼을 만듭니다. 값은 위에서 만들었던 y를 할당합니다.
data["MEDV"] = y

# data의 shape을 출력하여 확인합니다.
print(data.shape)

# data의 상위 5개 row(행)을 확인합니다.
data.head()

(506, 14)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

### Gradient Descent

Gradient Descent 방법을 이용해 문제를 해결해봅니다.  
먼저 직관적인 계산을 위해 feature의 각 변수들을 분리합니다.  
사용할 parameter들은 변수로 정의하는 게 좋을 것 같습니다. 우리는 num_epoch과 learning_rate를 사용할 것이며, 필요에 따라 추가해도 좋습니다. parameter들을 변수로 따로 빼둠으로써 실험을 보다 수월하게 수행할 수 있습니다.  
수업 시간에 다뤘던 numpy의 random 함수를 이용해 각 변수에 상응하는 가중치(weight)를 정의합니다.  
이제 error가 충분히 작아질 때까지 epoch을 돌면서 error를 구하고 가중치와 예측값(y_predict)을 업데이트합니다.

In [8]:
# 우선 feature를 각각 분리해 변수 x1 ~ x13에 담습니다.

x1 = X[:, 0] # CRIM
x2 = X[:, 1] # ZN
x3 = X[:, 2] # INDUS
x4 = X[:, 3] # CHAS
x5 = X[:, 4] # NOX
x6 = X[:, 5] # RM
x7 = X[:, 6] # AGE
x8 = X[:, 7] # DIS
x9 = X[:, 8] # RAD
x10 = X[:, 9] # TAX
x11 = X[:, 10] # PTRATIO
x12 = X[:, 11] # B
x13 = X[:, 12] # LSTAT

In [9]:
# 결과를 고정하기 위하여 seedf
np.random.seed(37)

# 가중치 업데이트 횟수인 num_epoch을 100000으로 정합니다.
# 충분히 수렴할 만큼 epoch이 돌아야 하므로 처음에는 임의의 큰 값으로 설정 후 조절합니다.
num_epoch = 100000

# 가중치 업데이트 속도와 관련된 learning_rate를 변수로 정의합니다.
# 학습에 있어 적절한 learning_rate를 정하는 것은 매우 중요한데,
# 너무 크면 오히려 발산할 수 있고 너무 작으면 학습이 느리거나 원하는 결과까지 도달하지 못할 수 있습니다.
# 보통 0.01~0.001정도로 시작해 결과에 따라 조절해갑니다.
learning_rate = 0.000003

# np.random을 이용해 가중치(w1 ~ w13)와 bias (b)를 정의합니다.
# -1 ~ +1 사이의 값중 랜덤으로 지정(초기화)합니다.
w1 = np.random.uniform(low=-1.0, high=1.0)
w2 = np.random.uniform(low=-1.0, high=1.0)
w3 = np.random.uniform(low=-1.0, high=1.0)
w4 = np.random.uniform(low=-1.0, high=1.0)
w5 = np.random.uniform(low=-1.0, high=1.0)
w6 = np.random.uniform(low=-1.0, high=1.0)
w7 = np.random.uniform(low=-1.0, high=1.0)
w8 = np.random.uniform(low=-1.0, high=1.0)
w9 = np.random.uniform(low=-1.0, high=1.0)
w10 = np.random.uniform(low=-1.0, high=1.0)
w11 = np.random.uniform(low=-1.0, high=1.0)
w12 = np.random.uniform(low=-1.0, high=1.0)
w13 = np.random.uniform(low=-1.0, high=1.0)
b = np.random.uniform(low=-1.0, high=1.0)

# epoch만큼 반복되는 for문을 선언합니다.
for epoch in range(num_epoch):
    # 현재의 w1 ~ w13과 x1 ~ x13을 각각 곱한 후 b를 더해 y_predict 변수에 저장합니다.
    # y_predict는 y를 예측한 값을 뜻합니다.
    y_predict = x1 * w1 + \
                x2 * w2 + \
                x3 * w3 + \
                x4 * w4 + \
                x5 * w5 + \
                x6 * w6 + \
                x7 * w7 + \
                x8 * w8 + \
                x9 * w9 + \
                x10 * w10 + \
                x11 * w11 + \
                x12 * w12 + \
                x13 * w13 + \
                b

                
    # 오차를 구하여 error에 저장합니다.
    # 오차는 MAE(Mean Absolute Error)를 사용합니다.
    error = np.abs(y_predict - y).mean()
    
    # 만약 오차가 5보다 작다면 for문을 마치고 알고리즘을 끝냅니다.
    if error < 5:
        # break는 for문을 바로 마칩니다.
        break

    # 학습 결과 모니터링을 위해 10000 epoch마다 error 값을 출력합니다.
    # error가 발산하는 지, 수렴하면 수렴 속도가 어떤 지 체크할 수 있습니다.
    if epoch % 10000 == 0:
        print("{0:5} error = {1:.5f}".format(epoch, error))

    # 오차를 이용해 w1 ~ w13, b 값을 learning_rate만큼 갱신합니다.
    w1 = w1 - learning_rate * ((y_predict - y) * x1).mean()
    w2 = w2 - learning_rate * ((y_predict - y) * x2).mean()
    w3 = w3 - learning_rate * ((y_predict - y) * x3).mean()
    w4 = w4 - learning_rate * ((y_predict - y) * x4).mean()
    w5 = w5 - learning_rate * ((y_predict - y) * x5).mean()
    w6 = w6 - learning_rate * ((y_predict - y) * x6).mean()
    w7 = w7 - learning_rate * ((y_predict - y) * x7).mean()
    w8 = w8 - learning_rate * ((y_predict - y) * x8).mean()
    w9 = w9 - learning_rate * ((y_predict - y) * x9).mean()
    w10 = w10 - learning_rate * ((y_predict - y) * x10).mean()
    w11 = w11 - learning_rate * ((y_predict - y) * x11).mean()
    w12 = w12 - learning_rate * ((y_predict - y) * x12).mean()
    w13 = w13 - learning_rate * ((y_predict - y) * x13).mean()
    
    b = b - learning_rate * (y_predict - y).mean()

# 수렴 조건으로 멈춘 후 마지막 error 값을 출력합니다.
print("----" * 10)
print("{0:5} error = {1:.5f}".format(epoch, error))

    0 error = 226.88855
10000 error = 5.40974
20000 error = 5.12939
30000 error = 5.02048
----------------------------------------
32329 error = 4.99999


In [10]:
# 최종 w1 ~ w13과 b를 이용해 y_predict를 다시 계산합니다.
y_predict = x1 * w1 + \
            x2 * w2 + \
            x3 * w3 + \
            x4 * w4 + \
            x5 * w5 + \
            x6 * w6 + \
            x7 * w7 + \
            x8 * w8 + \
            x9 * w9 + \
            x10 * w10 + \
            x11 * w11 + \
            x12 * w12 + \
            x13 * w13 + \
            b

# 최종 예측 결과를 result라는 변수에 저장합니다.
# 본래 데이터(data)를 복사해 result라는 변수를 만들고 'MEDV(predict)'라는 새 컬럼에 예측값을 넣어줍니다.
result = data.copy()
result["MEDV(predict)"] = y_predict

# result의 shape을 확인합니다.
print(result.shape)

# result의 첫 5 rows (행)를 확인합니다.
result.head()

(506, 15)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  MEDV(predict)  
0     15.3  396.90   4.98  24.0      30.309867  
1     17.8  396.90   9.14  21.6      26.860987  
2     17.8  392.83   4.03  34.7      29.320103  
3     18.7  394.63   2.94  33.4      29.694240  
4     18.7  396.90   5.33  36.2      28.928112

### Gradient Descent (use dot product)

만일 위의 과제가 너무 쉽다는 생각이 들면, **matrix의 [dot product](https://mathinsight.org/dot_product_matrix_notation)를 활용하여 다음과 같이 풀어볼 수 있습니다.**  
feature의 변수를 각각 정의하고 각 변수에 상응하는 가중치도 각각 정의해서 계산했던 것에 비해 훨씬 간결해졌음을 알 수 있습니다. 

In [11]:
# 가중치 업데이트 횟수인 num_epoch을 100000으로 정합니다.
# 충분히 수렴할 만큼 epoch이 돌아야 하므로 처음에는 임의의 큰 값으로 설정 후 조절합니다.
num_epoch = 100000

# 가중치 업데이트 속도와 관련된 learning_rate를 변수로 정의합니다.
# 학습에 있어 적절한 learning_rate를 정하는 것은 매우 중요한데,
# 너무 크면 오히려 발산할 수 있고 너무 작으면 학습이 느리거나 원하는 결과까지 도달하지 못할 수 있습니다.
# 보통 0.01~0.001정도로 시작해 결과에 따라 조절해갑니다.
learning_rate = 0.000003

# 행렬을 전치(transpose)한 값을 사전에 변수에 저장합니다.
# 앞으로 Feature(X)를 사용할 때에는 전부 전치(transpose)한 값을 사용할 예정입니다.
Xt = X.T

# shape의 1번째 값은 row (행)의 수, 즉, data의 수를 의미합니다.
# 이를 num_data에 저장합니다.
num_data = Xt.shape[1]

# np.random을 이용해 가중치(w)와 bias (b)를 정의합니다.
# 가중치는 dot_product를 사용할 것이므로 size=(13, 1)인 벡터로 정의합니다.
# -1 ~ +1 사이의 값중 랜덤으로 지정(초기화)합니다.
w = np.random.uniform(low=-1.0, high=1.0, size=(13, 1))
b = np.random.uniform(low=-1.0, high=1.0)

# epoch만큼 반복되는 for문을 선언합니다.
for epoch in range(num_epoch):
    # 전치(transpose)한 X와 w를 dot product 연산을 한 뒤 b를 더해 y_predict 변수에 저장합니다.
    # y_predict는 y를 예측한 값을 뜻합니다
    y_predict = np.dot(w.T, Xt) + b

    # 오차를 구하여 error에 저장합니다.
    # 오차는 MAE (Mean Absolute Error)를 사용합니다.
    error = np.abs(y_predict - y).mean()
    
    # 만약 오차가 5보다 작다면 for문을 마치고 알고리즘을 끝냅니다.
    if error < 5:
        # break는 for문을 바로 마칩니다.
        break

    # 학습 결과 모니터링을 위해 10000 epoch마다 error 값을 출력합니다.
    # error가 발산하는 지, 수렴하면 수렴 속도가 어떤 지 체크할 수 있습니다.
    if epoch % 10000 == 0:
        print("{0:5} error = {1:.5f}".format(epoch, error))

    # 오차를 이용해 w와 b를 learning_rate만큼 갱신합니다.
    w = w - learning_rate * np.dot(Xt, (y_predict - y).T) / num_data
    b = b - learning_rate * (y_predict - y).mean()

# 수렴 조건으로 멈춘 후 마지막 error 값을 출력합니다.
print("----" * 10)
print("{0:5} error = {1:.5f}".format(epoch, error))

    0 error = 173.24788
10000 error = 5.16250
----------------------------------------
14728 error = 4.99999


In [18]:
# 최종 w와 b를 이용해 y_predict를 다시 계산합니다.
y_predict = np.dot(w.T, Xt) + b

# y_predict의 모앙을 (506, 1)에서 506으로 바꿉니다.
# (이렇게 바꿔줘야) 아래에서 판다스 데이터프레임에 넣을 수 있습니다.
y_predict = y_predict.reshape(506)

# y_predict를 출력합니다.
y_predict

array([29.77093122, 24.88116222, 28.19736257, 27.07224868, 26.07649449,
       25.58161812, 20.42354618, 17.27547809,  8.91521071, 17.25639968,
       16.08267184, 20.32602601, 16.32813508, 26.17802038, 25.94864887,
       25.7163415 , 25.41973393, 22.87489061, 19.62960374, 24.73179804,
       18.95904093, 24.20284066, 21.23420576, 20.36948588, 22.45135125,
       19.08603715, 22.51578523, 19.28099579, 25.35860317, 25.69681782,
       17.01793369, 25.01753608,  9.83103077, 20.35338643, 16.66313556,
       24.49924461, 22.27223377, 23.12723836, 21.6172204 , 33.6461275 ,
       35.42063894, 22.59845851, 21.43101773, 20.60178002, 20.7356045 ,
       20.13533351, 17.42065797, 16.8489652 ,  8.19363239, 16.72259101,
       19.04471613, 23.00637426, 24.05236225, 21.28689121, 30.32268867,
       31.9241854 , 32.4859051 , 33.21946484, 23.09229813, 22.99146797,
       20.84252308, 21.5685302 , 26.29625913, 22.69431272, 23.97409122,
       31.99088244, 28.26282323, 23.28888094, 20.34998212, 23.49

In [19]:
# 최종 예측 결과를 result라는 변수에 저장합니다.
# 본래 데이터(data)를 복사해 result라는 변수를 만들고 'MEDV(predict)'라는 새 컬럼에 예측값을 넣어줍니다.
result = data.copy()
result["MEDV(predict)"] = y_predict

# result의 shape을 확인합니다.
print(result.shape)

# result의 첫 5 rows (행)를 확인합니다.
result.head()

(506, 15)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  MEDV(predict)  
0     15.3  396.90   4.98  24.0      29.770931  
1     17.8  396.90   9.14  21.6      24.881162  
2     17.8  392.83   4.03  34.7      28.197363  
3     18.7  394.63   2.94  33.4      27.072249  
4     18.7  396.90   5.33  36.2      26.076494

## 제출

과제를 다 끝내셨으면, datascience@dsschool.co.kr 로 제출해주시면 솔루션과 검토 결과를 드린 뒤, 다음 레벨 채널을 오픈해드립니다. 메일의 제목은 `[딥러닝 온라인 1:1 과외반 레벨2 과제 제출] 홍길동`과 같이 해주시면 감사하겠습니다.

과제 제출 후에 늦어도 24시간 이내에는 회신을 드립니다. 다만 과제의 난이도나 풀이에 따라 다소 시간이 걸릴 수 있다는 점 양해 부탁드립니다. 혹시나 다음 레벨로 초대를 못 받은 분들은 채널에 있는 튜터분에게 문의 주시면 다음 채널을 오픈해드립니다.

수업이나 과제 관련 질문, 기타 기수 변경, 수료증 문의는 담당 조교에서 문의 주시고 영수증 발급 등의 문의는 support@dsschool.co.kr 로 메일 주시면 감사하겠습니다.

In [ ]:
num_epoch = 100000

learning_rate = 0.000003

Xt = X.T

num_data = Xt.shape[1]

w = np.random.uniform(low=-1.0, high=1.0, size=(13, 1))
b = np.random.uniform(low=-1.0, high=1.0)

for epoch in range(num_epoch):
    # y_predict = X.dot(w) + b
    y_predict = np.dot(w.T, Xt) + b

    error = np.abs(y_predict - y).mean()
    
    if error < 5:
        break

    if epoch % 10000 == 0:
        print("{0:5} error = {1:.5f}".format(epoch, error))

    w = w - learning_rate * np.dot(Xt, (y_predict - y).T) / num_data
    b = b - learning_rate * (y_predict - y).mean()